# NUMPY NDARRAY

## Creating ndarrays

In [2]:
# import as required 
import pandas as pd
import numpy as np

In [24]:
# take a quick look 
data = np.random.randn(6).reshape(2,3)
data


array([[-1.39863807,  1.60042261, -0.91442479],
       [ 1.02754846,  0.22794911, -0.97110686]])

In [17]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [63]:
# Create one dimensional array, then reshape it
data1 = np.arange(8)
print('data1: \n', data1)
print('data1 reshape: \n', data1.reshape(2,4))
data1_1 = data1.reshape(2,4)
print('data1 still is: \n', data1,'\n','data1_1: \n', data1_1)

data1: 
 [0 1 2 3 4 5 6 7]
data1 reshape: 
 [[0 1 2 3]
 [4 5 6 7]]
data1 still is: 
 [0 1 2 3 4 5 6 7] 
 data1_1: 
 [[0 1 2 3]
 [4 5 6 7]]


In [64]:
data2 = np.zeros((3,6))
data2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## ndarrays Data Types 

In [67]:
data3 = np.array([1,3,5], dtype=np.int32) # without np int32 is not available
print(data3.dtype, data3)

int32 [1 3 5]


In [69]:
data4 = np.array([1,3,5], dtype=np.uint8)
print(data4.dtype, data4)

uint8 [1 3 5]
