# NUMPY NDARRAY

## Creating ndarrays

In [3]:
# import as required 
import pandas as pd
import numpy as np

In [4]:
# take a quick look 
data = np.random.randn(6).reshape(2,3)
data


array([[-0.41438645,  0.09680294,  0.7498302 ],
       [-0.41418904, -0.24263778,  1.23034497]])

In [5]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [6]:
# Create one dimensional array
data1 = np.arange(8)
data1


array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
# reshape() doesn't stick
data1.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
data1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
data2 = data1.reshape(2,4)
data2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
data2 = np.zeros((3,6))
data2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## ndarrays Data Types 

In [11]:
data3 = np.array([1,3,5], dtype=np.int32) # without np int32 is not available
print(data3.dtype, data3)

int32 [1 3 5]


In [12]:
data4 = np.array([1,3,5], dtype=np.uint8)
print(data4.dtype, data4)

uint8 [1 3 5]


## Operations 

In [13]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [15]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

## Basic Indexing and Slicing
### Scalars 

In [16]:
# This will change the actual arr (doing this with lists would create a new copy intead)
arr = np.arange(10)
print(arr)
new_element = 1
arr_slice = arr[5:7] 
arr_slice[:] = new_element
print(arr[0:9] == new_element)
arr[:]

[0 1 2 3 4 5 6 7 8 9]
[False  True False False False  True  True False False]


array([0, 1, 2, 3, 4, 1, 1, 7, 8, 9])

In [17]:
# copy an array or a slice thereof
arr = np.arange(10)
arr_slice = arr.copy()
arr_slice[5:9] = new_element
print(arr)
print(arr_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 1 1 1 1 9]


### Vectors 

In [18]:
# 2d array 
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('0th e:', arr2d[0]) # an element is a 1D list
print('shape:', arr2d.shape)

0th e: [1 2 3]
shape: (3, 3)


In [19]:
print(arr2d[:2]) # slices along the 1st axis (y), so shows col 0, 1 
print(arr2d[:2, 1:]) # then slices along 2nd axis (x), so shows col 0 1, element 1 2 

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [20]:
#                |-----------------2--------------------| 
#                 |-------2-------|   
#                  |--3--|   
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
print(arr3d[0]) # an element is a 2D list, etc
print(arr3d.shape)


[[1 2 3]
 [4 5 6]]
(2, 2, 3)


In [21]:
print(arr3d)
print('-------------------')
print('1:', arr3d[:1])         #slices along the 1st axis (y sky)
print('-------------------')
print('2:', arr3d[:1, 1:])     #       along 2nd axis (x)
print('-------------------')
print('3:', arr3d[:1, 1:, 1:]) #       along 3nd axis (z) 


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
-------------------
1: [[[1 2 3]
  [4 5 6]]]
-------------------
2: [[[4 5 6]]]
-------------------
3: [[[5 6]]]


### Fancy Indexing  

In [22]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i*2

arr

array([[ 0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.],
       [10., 10., 10., 10.],
       [12., 12., 12., 12.],
       [14., 14., 14., 14.]])

In [23]:
arr[[-5,6,0]]

array([[ 6.,  6.,  6.,  6.],
       [12., 12., 12., 12.],
       [ 0.,  0.,  0.,  0.]])

In [24]:
arr = np.arange(32).reshape((8,4))
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [25]:
arr[[2],[3]]
# array([11])
arr[2,3]
# 11
arr[[2,3,1], [3,3,1]]
# array([11, 15, 5])

array([11, 15,  5])

### Transposing Arrays and Swapping Axes

In [41]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
arr.T

#array([[0, 3],
#       [1, 4],
#       [2, 5]])

arr.swapaxes(1,0)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [43]:
np.dot(arr.T, arr)

array([[ 9, 12, 15],
       [12, 17, 22],
       [15, 22, 29]])

### Universal Functions uFuncs

In [68]:
print(arr)
print(np.sqrt(arr))
print(np.exp(arr))


[[0 1 2]
 [3 4 5]]
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]
[[  1.           2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003 148.4131591 ]]


In [63]:
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x, y)

array([0.28996932, 0.03707298, 1.16594698, 1.5433177 , 1.86855693,
       0.78827813, 0.32722745, 1.31798571])

In [67]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])